classdef setCoordinates < hgsetget & handle
%SETCOORDINATES Class for defining required data on the given picture.  

    properties(Access = protected)
        mainObj;
        hCoordinateFigure;
        hCoordinateDataPanel;
        hAxesDataTable;
        hCoordinateAxesPanel;
        hXaxesPopupmenu;
        hYaxesPopupmenu;
        tableData;
    end
    
    methods
        function scObj = setCoordinates(obj) 
            % Construct a setCoordinates object and setup required uicontrols 
            scObj.mainObj = obj;
            switch scObj.mainObj.coordinateFigState
                case 'new'
                    scObj.tableData = zeros(3,4);
                case 'current'
                    if isempty(scObj.mainObj.coordinateHistory)
                        scObj.tableData = scObj.mainObj.xyCoordinatesMatrix;
                    else
                        scObj.tableData = scObj.mainObj.coordinateHistory{get(scObj.mainObj.hCurveList,'userdata')};
                    end
            end
            X = get(scObj.mainObj.hMainFig,'pos');
            scObj.hCoordinateFigure = figure('units','pixels',...
                                             'menubar','none',...
                                             'toolbar','none',...
                                             'pos',...
                                             [X(1)+X(3)/3 X(2)+X(4)/4 X(3)*0.4 X(4)*0.5],...
                                             'numbertitle','off',...
                                             'name','Set Coordinates',...
                                             'tag','hCoordinateFigure',...
                                             'resize','off',...
                                             'handlevisibility','callback',...
                                             'CreateFcn','movegui(''center'')',...
                                             'DeleteFcn',@(varargin)figureDeleteFcn(scObj,varargin));
            scObj.hCoordinateDataPanel = uipanel('parent',scObj.hCoordinateFigure,...
                                                 'title','XY-Data',...
                                                 'units','normalized',...
                                                 'pos',[0.05 0.55 0.90 0.35],...
                                                 'backgroundcolor',get(gcf,'color'),...
                                                 'highlightcolor','white',...
                                                 'tag','hCoordinateDataPanel');
            colNames = {'X-Value','Y-Value',' X-Coordinate ',' Y-Coordinate '};
            rowNames = {'Origin','X-Axis','Y-Axis'};
            colfmt = {'numeric','numeric','numeric','numeric'};
            colEdit = [true true];
            scObj.hAxesDataTable = uitable(scObj.hCoordinateDataPanel,...
                                           'units','normalized',...
                                           'pos', [0.01 0.015 0.98 0.99],...
                                           'data',scObj.tableData,...
                                           'tag','hAxesDataTable',...
                                           'columnname', colNames,...
                                           'rowname',rowNames,...
                                           'columnformat', colfmt,...
                                           'columneditable', colEdit);
            uicontrol('parent',scObj.hCoordinateFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.1 0.4 0.15 0.075], ...
                      'string','Point 1',...
                      'tag','point1',...
                      'callback',@(varargin)setPoint(scObj,varargin));
            uicontrol('parent',scObj.hCoordinateFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.425 0.4 0.15 0.075], ...
                      'string','Point 2',...
                      'tag','point2',...
                      'callback',@(varargin)setPoint(scObj,varargin));                                  
            uicontrol('parent',scObj.hCoordinateFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.75 0.4 0.15 0.075], ...
                      'string','Point 3',...
                      'tag','point3',...
                      'callback',@(varargin)setPoint(scObj,varargin));                             
            scObj.hCoordinateAxesPanel = uipanel('parent',scObj.hCoordinateFigure,...
                                                 'title','XY-Axes',...
                                                 'units','normalized',...
                                                 'pos',[0.05 0.15 0.90 0.2],...
                                                 'backgroundcolor',...
                                                  get(gcf,'color'),...
                                                 'highlightcolor','white',...
                                                 'tag','hCoordinateAxesPanel');                             
            uicontrol('parent',scObj.hCoordinateAxesPanel,...
                      'style','text',...
                      'string','X-Scale',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.01 0.7 0.25 0.25]);
            uicontrol('parent',scObj.hCoordinateAxesPanel,...
                      'style','text',...
                      'string','Y-Scale',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.74 0.7 0.25 0.25]);                               
            scObj.hXaxesPopupmenu = uicontrol(scObj.hCoordinateAxesPanel,...
                                              'style','popupmenu',...
                                              'string',{'Linear','Log'},...
                                              'units','normalized',...
                                              'value',1,...
                                              'pos',[0.01 0.25 0.25 0.25],...
                                              'tag','hXaxesPopupmenu');
            scObj.hYaxesPopupmenu = uicontrol('parent',scObj.hCoordinateAxesPanel,...
                                              'style','popupmenu',...
                                              'string',{'Linear','Log'},...
                                              'units','normalized',...
                                              'value',1,...
                                              'pos',[0.74 0.25 0.25 0.25],...
                                              'tag','hYaxesPopupmenu');
            if ~isempty(scObj.mainObj.scaleHistory)                          
                if (strcmp(scObj.mainObj.coordinateFigState,'current')) &&...
                   (sum(scObj.mainObj.scaleHistory{get(scObj.mainObj.hCurveList,'userdata')}) > 0)
                    set(findobj('tag','hXaxesPopupmenu'),...
                        'Value',scObj.mainObj.scaleHistory{get(scObj.mainObj.hCurveList,'userdata')}(1));
                    set(findobj('tag','hYaxesPopupmenu'),...
                        'Value',scObj.mainObj.scaleHistory{get(scObj.mainObj.hCurveList,'userdata')}(2));
                end
            elseif isempty(scObj.mainObj.scaleHistory) &&...
                   sum(scObj.mainObj.xyScaleMatrix) > 0
                if (strcmp(scObj.mainObj.coordinateFigState,'current'))
                    set(findobj('tag','hXaxesPopupmenu'),...
                        'Value',scObj.mainObj.xyScaleMatrix(1));
                    set(findobj('tag','hYaxesPopupmenu'),...
                        'Value',scObj.mainObj.xyScaleMatrix(2));
                end
            end                              
            uicontrol('parent',scObj.hCoordinateFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.05 0.05 0.15 0.075], ...
                      'string','Ok',...
                      'callback',@(varargin)coordinatesOkCancelPress(scObj,varargin));                         
            uicontrol('parent',scObj.hCoordinateFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.8 0.05 0.15 0.075], ...
                      'string','Cancel',...
                      'callback',@(varargin)coordinatesOkCancelPress(scObj,varargin)); 
            set(findobj('label','Coordinate Settings'),'enable','on');  
        end
    end
    methods(Access = protected)
        setPoint(scObj,varargin);
        coordinatesOkCancelPress(scObj,varargin);
        function figureDeleteFcn(scObj,varargin)
            % destruct a SetCoordinates object, class destructor
            if isvalid(scObj) && isobject(scObj)
                delete(scObj)
            end
        end
    end
    
end

