function movePoint(scObj,varargin)
%MOVEPOINT function moves user defined point inside the picture frame. 
    h1 = line('parent',get(scObj.mainObj.hMainFig,'currentaxes'),...
              'xdata',[],...
              'ydata',[],...
              'visible','off',...
              'clipping','off',...
              'color','c',...
              'linestyle','none',...
              'marker','none');
    data = scObj.mainObj.xyCoordinatesMatrix;
    xyScaleMatrix = scObj.mainObj.xyScaleMatrix;
    colorDataInd = scObj.mainObj.colorDataInd;
    set(gcf,'WindowButtonDownFcn',@(varargin)wbdFcn(scObj,varargin),...
        'WindowKeyPressFcn',@kpFcn)
        
    %------------------------------------------------------
    function wbdFcn(scObj,varargin)
        if strcmp(get(gcf,'selectiontype'),'normal')
            pt = get(get(scObj.mainObj.hMainFig,'currentaxes'),'currentpoint');
            pts = [pt(1,1),pt(1,2)];
            [xOut,yOut] = GSGUI.GraphScannerGUI.outOfRange(data,pts(1),pts(2));
            if (xOut && xyScaleMatrix(1) == 2) || (yOut && xyScaleMatrix(2) == 2)
                return
            end
            x = scObj.mainObj.xDataHistory{get(scObj.mainObj.hCurveList,'userdata')};
            y = scObj.mainObj.yDataHistory{get(scObj.mainObj.hCurveList,'userdata')};
            dist = (x-pts(1)).^2+(y-pts(2)).^2;
            [val,xi] = min(dist);
            xx = x;
            yy = y;
            xx(xi) = [];
            yy(xi) = [];
            set(findobj('tag','plotting'),...
                'xdata',xx,...
                'ydata',yy,...
                'marker','o',...
                'color',colorDataInd.linecolor,...
                'markeredgecolor',colorDataInd.markerecolor,...
                'markerfacecolor',colorDataInd.markerfcolor,...
                'markersize',8);  
            set(h1,'xdata',x(xi),...
                'ydata',y(xi),...
                'marker','o',...
                'color',colorDataInd.linecolor,...
                'markeredgecolor',colorDataInd.markerecolor,...
                'markerfacecolor',colorDataInd.markerfcolor,...
                'markersize',8,...
                'visible','on'); 
            newCoordinates = GSGUI.GraphScannerGUI.calculation(x,y,data,xyScaleMatrix);
            set(scObj.mainObj.hSelectedXPoint,'string',...
                num2str(newCoordinates(xi,1),'%10.6e'));
            set(scObj.mainObj.hSelectedYPoint,'string',...
                num2str(newCoordinates(xi,2),'%10.6e'));
            set(gcf,'WindowButtonMotionFcn',@(varargin)wbmFcn(scObj,varargin),...
                'WindowButtonUpFcn',@(varargin)wbuFcn(scObj,varargin));   
        elseif strcmp(get(gcf,'SelectionType'),'alt')
            set(gcf,'WindowButtonMotionFcn','',...
                'WindowButtonUpFcn','',...
                'WindowButtonDownFcn','',...
                'WindowKeyPressFcn','');
            if ishandle(h1)
                delete(h1)
            end
        end

        %--------------------------------------------------
        function wbmFcn(scObj,varargin)
            try
                pt = get(get(scObj.mainObj.hMainFig,'currentaxes'),'currentpoint');
                pts = [pt(1,1),pt(1,2)];
                [xOut,yOut] = GSGUI.GraphScannerGUI.outOfRange(data,pts(1),pts(2));
                if (xOut && xyScaleMatrix(1) == 2) || (yOut && xyScaleMatrix(2) == 2)
                    set(gcf,'WindowButtonMotionFcn','',...
                        'WindowButtonUpFcn','',...
                        'WindowButtonDownFcn','',...
                        'WindowKeyPressFcn','');
                    if ishandle(h1)
                        delete(h1)
                    end
                    return
                end
                x(xi) = pts(1);
                y(xi) = pts(2);
                newCoordinates = GSGUI.GraphScannerGUI.calculation(x,y,data,xyScaleMatrix);
                set(h1,'xdata',pts(1),'ydata',pts(2));
                set(scObj.mainObj.hSelectedXPoint,'string',...
                    num2str(newCoordinates(xi,1),'%10.6e'));
                set(scObj.mainObj.hSelectedYPoint,'string',...
                    num2str(newCoordinates(xi,2),'%10.6e'));
            catch ME
                errordlg(ME.message,ME.identifier)
            end
        end

        %--------------------------------------------------
        function wbuFcn(scObj,varargin)
            if strcmp(get(gcf,'selectiontype'),'normal')
                try
                    pts = [get(h1,'xdata'),get(h1,'ydata')];
                    [xOut,yOut] = GSGUI.GraphScannerGUI.outOfRange(data,pts(1),pts(2));
                    if (xOut && xyScaleMatrix(1) == 2) || (yOut && xyScaleMatrix(2) == 2)
                        set(gcf,'WindowButtonMotionFcn','',...
                            'WindowButtonUpFcn','',...
                            'WindowButtonDownFcn','',...
                            'WindowKeyPressFcn','');
                        if ishandle(h1)
                            delete(h1)
                        end
                        return
                    end                   
                    [x,y,place] = GSGUI.GraphScannerGUI.checkDistance(x,y,pts,'move',xi);
                    scObj.mainObj.xDataHistory{get(scObj.mainObj.hCurveList,'userdata')} = x;
                    scObj.mainObj.yDataHistory{get(scObj.mainObj.hCurveList,'userdata')} = y;
                    newCoordinates = GSGUI.GraphScannerGUI.calculation(x,y,data,xyScaleMatrix);
                    scObj.mainObj.xyDataValues{get(scObj.mainObj.hCurveList,'userdata')} = newCoordinates;             
                    set(scObj.mainObj.hCurveDataTable,'data',newCoordinates);             
                    notify(scObj.mainObj,'updateGraph');
                    set(h1,'marker','none',...
                        'xdata',[],...
                        'ydata',[],...
                        'visible','off');
                    set(scObj.mainObj.hSelectedXPoint,'string',...
                        num2str(newCoordinates(place,1),'%10.6e'));
                    set(scObj.mainObj.hSelectedXPoint,'tooltipstring',...
                        sprintf('x-value\nLast modification: point moved to...'));
                    set(scObj.mainObj.hSelectedYPoint,'string',...
                        num2str(newCoordinates(place,2),'%10.6e'));
                    set(scObj.mainObj.hSelectedYPoint,'tooltipstring',...
                        sprintf('y-value\nLast modification: point moved to...'));
                    set(gcf,'WindowButtonMotionFcn','',...
                        'WindowButtonUpFcn','');
                    scObj.mainObj.isGuiAlter = true;
                catch ME
                    errordlg(ME.message,ME.identifier)
                end
            else
                set(gcf,'WindowButtonMotionFcn','',...
                        'WindowButtonUpFcn','');
                return
            end
        end
    end
    %------------------------------------------------------------------
    function kpFcn(varargin)
        set(gcf,'WindowButtonMotionFcn','',...
            'WindowButtonUpFcn','',...
            'WindowButtonDownFcn','',...
            'WindowKeyPressFcn','');
        if ishandle(h1)
            delete(h1)
        end
        return
    end
end 


