classdef setCurve < hgsetget & handle
%SETCURVE Class for defining and modifing points on the given picture. 
    
    properties(Access = protected)
        mainObj;
    end
    
    methods
        function scObj = setCurve(obj)
            % Construct a SetCurve object and setup required uicontrols
            scObj.mainObj = obj;
            if isempty(findobj('tag','on'))
                uimenu('parent',scObj.mainObj.hNewCurveMenu,...
                       'handlevisibility','on',...
                       'label','New Curve',...
                       'callback',@(varargin)setNewCurve(scObj,varargin),...
                       'tag','on',...
                       'separator','off',....
                       'DeleteFcn',@(varargin)uimenuDeleteFcn(scObj,varargin));
                set(findobj('tag','UIcmcurve'),...
                    'enable','on',...
                    'callback',@(varargin)setNewCurve(scObj,varargin));
                uimenu('parent',scObj.mainObj.hNewCurveMenu,...
                       'separator','on',...
                       'handlevisibility','on',...
                       'label','Add Point',...
                       'callback',@(varargin)addNewPoint(scObj,varargin),...
                       'enable','off',...
                       'tag','on'); 
                uimenu('parent',scObj.mainObj.hNewCurveMenu,...
                       'handlevisibility','on',...
                       'label','Delete Point',...
                       'callback',@(varargin)deletePoint(scObj,varargin),...
                       'enable','off',...
                       'tag','on');  
                uimenu('parent',scObj.mainObj.hNewCurveMenu,...
                       'handlevisibility','on',...
                       'label','Move Point',...
                       'callback',@(varargin)movePoint(scObj,varargin),...
                       'enable','off',...
                       'tag','on');       
                uimenu('parent',scObj.mainObj.hNewCurveMenu,...
                       'handlevisibility','on',...
                       'label','Select Point',...
                       'callback',@(varargin)selectPoint(scObj,varargin),...
                       'enable','off',...
                       'tag','on');
                set(scObj.mainObj.hCurveDataTable,...
                    'cellselectioncallback',@(varargin)cellSelection(scObj,varargin));
            end
        end
    end
    methods(Access = protected)
        scObj = setNewCurve(scObj,varargin);
        addNewPoint(scObj,varargin);
        deletePoint(scObj,varargin);
        movePoint(scObj,varargin);
        selectPoint(scObj,varargin);
        cellSelection(scObj,varargin);
        function uimenuDeleteFcn(scObj,varargin)
            if isvalid(scObj) && isobject(scObj)
                delete(scObj)
            end
        end
    end
    
end

