classdef setting < hgsetget & handle
%SETTING Class for defining particular setting to the current plot.
    
    properties(Access = protected)
        mainObj;
        hSettingFigure;
        hSettingPanel;
        hCurveNameSet;
        hDisplayGrid;
        hDisplayLine;
        hDisplayMarker;
        hXTickNP;
        hYTickNP;
        hXLabel;
        hYLabel;
    end
    
    methods
        function sObj = setting(obj)
            % Construct a setting object and setup required uicontrols
            sObj.mainObj = obj;
            X = get(sObj.mainObj.hMainFig,'pos');
            sObj.hSettingFigure = figure('units','pixels',...
                                         'menubar','none',...
                                         'toolbar','none',...
                                         'pos',...
                                         [X(1)+X(3)/3 X(2)+X(4)/3 X(3)/2 X(4)/2],...
                                         'numbertitle','off',...
                                         'name','Settings',...
                                         'tag','hSettingFigure',...
                                         'visible','on',...
                                         'resize','off',...
                                         'CreateFcn','movegui(''center'')',...
                                         'DeleteFcn',...
                                         @(varargin)figureDeleteFcn(sObj,varargin));                  
            sObj.hSettingPanel = uipanel('parent',sObj.hSettingFigure,...
                                         'title','Preferences',...
                                         'units','normalized',...
                                         'pos',[0.05 0.075 0.9 0.88],...
                                         'backgroundcolor',get(gcf,'color'),...
                                         'highlightcolor','white',...
                                         'tag','hSettingPanel');
            uicontrol('parent',sObj.hSettingPanel,...
                      'style','text',...
                      'string','Curve Information:',...
                      'units','normalized',...                 
                      'backgroundcolor',get(gcf,'color')',...
                      'pos',[0.05 0.88 0.3 0.075],...
                      'horizontalalignment','left');
            if isempty(sObj.mainObj.curveNames)
                sObj.hCurveNameSet = uicontrol(sObj.hSettingPanel,...
                                               'style','edit',...
                                               'tag','hCurveNameSet',...
                                               'backgroundcolor','white',...
                                               'units','normalized',...
                                               'pos',[0.235 0.9 0.2 0.075],...
                                               'string',sObj.mainObj.defaultCurveName{1});
            else
                sObj.hCurveNameSet = uicontrol(sObj.hSettingPanel,...
                                               'style','edit',...
                                               'tag','hCurveNameSet',...
                                               'backgroundcolor','white',...
                                               'units','normalized',...
                                               'pos',[0.235 0.9 0.2 0.075],...
                                               'string',sObj.mainObj.curveNames{get(sObj.mainObj.hCurveList,'userdata')});
            end
            sObj.hDisplayLine = uicontrol(sObj.hSettingPanel,...
                                          'style','check',...
                                          'backgroundcolor',get(gcf,'color'),...
                                          'String','Display Line',...
                                          'units','normalized',...
                                          'tag','hDisplayLine',...
                                          'value',1,...
                                          'pos',[0.05 0.75 0.3 0.075]);
            sObj.hDisplayMarker = uicontrol(sObj.hSettingPanel,...
                                            'style','check',...
                                            'backgroundcolor',get(gcf,'color'),...
                                            'String','Display Marker',...
                                            'tag','hDisplayMarker',...
                                            'units','normalized',...
                                            'value',1,...
                                            'pos',[0.05 0.6 0.3 0.075]);
            uicontrol(sObj.hSettingPanel,...
                      'style','push',...
                      'background',get(gcf,'color'),...
                      'string','Set line color',...
                      'tag','linecolor',...
                      'userdata',[0 0 0],...
                      'units','normalized',...
                      'pos',[0.235 0.75 0.195 0.075],...
                      'callback',@(varargin)setColor(sObj,varargin)); 
            uicontrol(sObj.hSettingPanel,...
                      'style','push',...
                      'background',get(gcf,'color'),...
                      'string','Set color',...
                      'tag','markerfstyle',...
                      'userdata',[0 0 1],...
                      'units','normalized',...
                      'pos',[0.235 0.6 0.195 0.075],...
                      'callback',@(varargin)setColor(sObj,varargin));                          
            uicontrol(sObj.hSettingPanel,...
                      'style','push',...
                      'background',get(gcf,'color'),...
                      'string','Set color',...
                      'tag','markerestyle',...
                      'userdata',[1 0 0],...
                      'units','normalized',...
                      'pos',[0.235 0.5 0.195 0.075],...
                      'callback',@(varargin)setColor(sObj,varargin));
            sObj.hDisplayGrid = uicontrol(sObj.hSettingPanel,...
                                          'style','check',...
                                          'string','Display Grid',...
                                          'backgroundcolor',get(gcf,'color'),...
                                          'tag','hDisplayGrid',...
                                          'value',0,...
                                          'units','normalized',...
                                          'pos',[0.5 0.9 0.175 0.075],...
                                          'enable','on');                          
            uicontrol(sObj.hSettingPanel,...
                      'style','text',...
                      'string','Number of spacings:',...
                      'units','normalized',...
                      'HorizontalAlignment','left',...
                      'backgroundcolor',get(gcf,'color')',...
                      'pos',[0.5 0.8 0.2 0.05]);
            uicontrol(sObj.hSettingPanel,...
                      'style','text',...
                      'string','X-axis',...
                      'units','normalized',...                 
                      'backgroundcolor',get(gcf,'color')',...
                      'pos',[0.8 0.8 0.075 0.05]);
            uicontrol(sObj.hSettingPanel,...
                      'style','text',...
                      'string','Y-axis',...
                      'units','normalized',...                 
                      'backgroundcolor',get(gcf,'color')',...
                      'pos',[0.8 0.7 0.075 0.05]);
            sObj.hXTickNP = uicontrol(sObj.hSettingPanel,...
                                      'style','edit',...
                                      'tag','hXTickNP',...
                                      'backgroundcolor','white',...
                                      'units','normalized',...
                                      'pos',[0.7 0.8 0.075 0.065],...
                                      'visible','on',...
                                      'string','1',...
                                      'userdata',1);   
            sObj.hYTickNP = uicontrol(sObj.hSettingPanel,...
                                      'style','edit',...
                                      'tag','hYTickNP',...
                                      'backgroundcolor','white',...
                                      'units','normalized',...
                                      'pos',[0.7 0.7 0.075 0.065],...
                                      'visible','on',...
                                      'string','1',...
                                      'userdata',1);
            uicontrol(sObj.hSettingPanel,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.05 0.125 0.15 0.075], ...
                      'string','Ok',...
                      'callback',@(varargin)settingOkCancelPress(sObj,varargin));                         
            uicontrol(sObj.hSettingPanel,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.8 0.125 0.15 0.075], ...
                      'string','Cancel',...
                      'callback',@(varargin)settingOkCancelPress(sObj,varargin));
            uicontrol('parent',sObj.hSettingPanel,...
                      'style','text',...
                      'string','X-Axis Label:',...
                      'HorizontalAlignment','left',...
                      'units','normalized',...                 
                      'backgroundcolor',get(gcf,'color')',...
                      'pos',[0.5 0.572 0.15 0.05],...
                      'horizontalalignment','left'); 
            uicontrol('parent',sObj.hSettingPanel,...
                      'style','text',...
                      'string','Y-Axis Label:',...
                      'HorizontalAlignment','left',...
                      'units','normalized',...                 
                      'backgroundcolor',get(gcf,'color')',...
                      'pos',[0.5 0.472 0.15 0.05],...
                      'horizontalalignment','left');
            sObj.hXLabel = uicontrol(sObj.hSettingPanel,...
                                     'style','edit',...
                                     'tag','hXLabel',...
                                     'backgroundcolor','white',...
                                     'units','normalized',...
                                     'pos',[0.7 0.572 0.1 0.075],...
                                     'string',sObj.mainObj.xAxisLabel);
            sObj.hYLabel = uicontrol(sObj.hSettingPanel,...
                                     'style','edit',...
                                     'tag','hYLabel',...
                                     'backgroundcolor','white',...
                                     'units','normalized',...
                                     'pos',[0.7 0.472 0.1 0.075],...
                                     'string',sObj.mainObj.yAxisLabel);                     
            if strcmp(get(findobj('tag','plotting'),'linestyle'),'none')
                set(sObj.hDisplayLine,'value',0);
            else
                set(sObj.hDisplayLine,'value',1);
            end
            if strcmp(get(findobj('tag','plotting'),'marker'),'none')
                set(sObj.hDisplayMarker,'value',0);
            else
                set(sObj.hDisplayMarker,'value',1);
            end
            if strcmp(get(findobj('tag','plotrec'),'visible'),'off')
                set(sObj.hDisplayGrid,'value',0);
            else
                if isempty(findobj('tag','plotrec'))
                    set(sObj.hDisplayGrid,'value',0);
                else
                    set(sObj.hDisplayGrid,'value',1);
                end
            end
            set(sObj.hXTickNP,'string',num2str(sObj.mainObj.gridSpacing(1)));
            set(sObj.hYTickNP,'string',num2str(sObj.mainObj.gridSpacing(2)));
        end
    end
    methods(Access = protected)
        setColor(sObj,varargin);
        settingOkCancelPress(sObj,varargin);
        function figureDeleteFcn(sObj,varargin)
            if isvalid(sObj) && isobject(sObj)
                delete(sObj)
            end
        end
            
    end
    
end

