classdef resize < hgsetget & handle
%RESIZE Class for resizing current figure on the GUI panel.
    
    properties(Access = protected)
        mainObj;
        hResizeFigure;
        pictureSize;
    end
    
    methods
        function rObj = resize(obj)
            % Contruct a Resize object and setup required uicontrols.
            rObj.mainObj = obj;
            X = get(rObj.mainObj.hMainFig,'pos');
            hAxes = get(rObj.mainObj.hMainFig,'currentaxes');
            rObj.pictureSize = get(hAxes,'pos');
            rObj.hResizeFigure = figure('units','pixels',...
                                        'menuBar','none',...
                                        'toolbar','none',...
                                        'pos',...
                                        [X(1)+X(3)/3 X(2)+X(4)/3 X(3)*0.2 X(4)*0.3],...
                                        'numbertitle','off',...
                                        'name','Resize',...
                                        'tag','resizefigure',...
                                        'visible','on',...
                                        'resize','off',...
                                        'CreateFcn','movegui(''center'')',...
                                        'DeleteFcn',@(varargin)figureDeleteFcn(rObj,varargin));                  
            uipanel('parent',rObj.hResizeFigure,...
                    'title','Pixel size',...
                    'units','normalized',...
                    'pos',[0.05 0.3 0.9 0.65],...
                    'backgroundcolor',get(gcf,'color'),...
                    'highlightcolor','white');
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','text',...
                      'string','Width:',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.1 0.7 0.2 0.1]);
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','edit',...
                      'string',num2str(floor(rObj.pictureSize(3))),...
                      'units','normalized',...
                      'tag','pixelsizewidth',...
                      'backgroundcolor','white',...
                      'pos',[0.3 0.725 0.25 0.1]);
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','text',...
                      'string','Heigth:',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.1 0.55 0.2 0.1]);
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','edit',...
                      'string',num2str(floor(rObj.pictureSize(4))),...
                      'units','normalized',...
                      'tag','pixelsizeheigth',...
                      'backgroundcolor','white',...
                      'pos',[0.3 0.575 0.25 0.1]);
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','text',...
                      'string','pixels',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.55 0.7 0.2 0.1]);  
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','text',...
                      'string','pixels',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.55 0.55 0.2 0.1]);
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','checkbox',...
                      'units','normalized',...
                      'backgroundcolor',get(gcf,'color'),...
                      'pos',[0.1 0.35 0.45 0.1], ...
                      'string','Fit to Screen',...
                      'value',0,...
                      'callback',@(varargin)resizeFitToScreen(rObj,varargin));       
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.25 0.1 0.2 0.1], ...
                      'string','Ok',...
                      'callback',@(varargin)resizeOkCancelPress(rObj,varargin));     
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.5 0.1 0.2 0.1], ...
                      'string','Reset',...
                      'callback',@(varargin)resizeResetPress(rObj,varargin));                           
            uicontrol('parent',rObj.hResizeFigure,...
                      'style','push',...
                      'units','normalized',...
                      'background',get(gcf,'color'),...
                      'pos',[0.75 0.1 0.2 0.1], ...
                      'string','Cancel',...
                      'callback',@(varargin)resizeOkCancelPress(rObj,varargin));
        end
    end
    methods(Access = protected)
       resizeOkCancelPress(rObj,varargin);
       resizeResetPress(rObj,varargin);
       resizeFitToScreen(rObj,varargin);
       function figureDeleteFcn(rObj,varargin)
           % Class destructor
           if isvalid(rObj) && isobject(rObj)
               delete(rObj)
           end
       end
    end
end

