function AddTrackSlider(hfig,pos1,pos2)

movieData = get(hfig,'userdata');

movieData.TrackSlider = uicontrol(hfig, ...
    'tag', 'TRACKSLIDER', ...
    'enable', 'off', ...
    'style', 'slider', ...
    'Position', pos1, ... %[60 0 100 20], ...
    'callback', @ChooseTrack); 

movieData.TrackSliderText = uicontrol(hfig, ...
    'style','text', ...
    'tag', 'TRACKSLIDERTEXT', ...
    'string', '', ...
    'Position', pos2);

set(hfig,'userdata', movieData);

end

