function createToolbar(hfig)
movieData = get(hfig, 'userdata');
icons    = mergefields(load('audiotoolbaricons'), load('mplay_icons'), load('BenIcons'));
% CR       = sprintf('\n');
htoolbar = uitoolbar(hfig);         % Create toolbar
setappdata(htoolbar,'icons',icons); % Store icons in toolbar appdata

uipushtool(htoolbar, ...
    'cdata', icons.goto_start_default, ...
    'tooltip','Go to start', ...
    'separator','on', ...
    'click', @gotoFirstFrame);

% uipushtool(htoolbar, ...
%     'cdata', icons.rewind_default, ...
%     'tooltip','Rewind', ...
%     'click', @cb_rewind);

uipushtool(htoolbar, ...
    'cdata', icons.step_back, ...
    'tooltip','Step back', ...
    'click', @previousFrame);

% uipushtool(htoolbar, ...
%     'cdata', icons.stop_default, ...
%     'tooltip','Stop', ...
%     'click', @cb_stop);
% 'click', @cb_stop); cb_play
% changed behavior of Stop key from Stop to Play/Pause
% 7/6/2009 Ben Snyder

uipushtool(htoolbar, ...
    'cdata', icons.play_on, ...
    'tooltip','Play', ...
    'tag','Play/Pause', ...
    'click', @playMovie);

uipushtool(htoolbar, ...
    'cdata', icons.step_fwd, ...
    'tooltip','Step forward', ...
    'click', @nextFrame);

% uipushtool(htoolbar, ...
%     'cdata', icons.ffwd_default, ...
%     'tooltip','Fast forward', ...
%     'click', @cb_ffwd);

uipushtool(htoolbar, ...
    'cdata', icons.goto_end_default, ...
    'tooltip','Go to end', ...
    'click', @gotoLastFrame);

% uipushtool(htoolbar, ...
%     'cdata', icons.jump_to, ...
%     'separator','on', ...
%     'tooltip','Jump to...', ...
%     'click', @cb_jumpto);

uipushtool(htoolbar, ...
    'cdata', icons.TIcon, ...
    'separator', 'on', ...
    'tooltip','Show/Hide Path', ...
    'tag','Show/Hide Path', ...
    'click', @showPath);

% uipushtool(htoolbar, ...
%     'cdata', icons.PIcon, ...
%     'tooltip','Set path display prefs', ...
%     'tag','Set path display prefs', ...
%     'click', @cb_path_prefs);

uipushtool(htoolbar, ...
    'cdata', icons.ZoomOff, ...
    'tooltip','Zoom In/Out', ...
    'tag','ZOOM', ...
    'click', @setZoom);


movieData.htoolbar = htoolbar;

set(hfig,'userdata', movieData);

return;

end

