function correct_attributes = parse_BinData_fields(input_attributes)

persistent bindata_fieldnames;

if(isempty(bindata_fieldnames))
    freqfrac_bases = { ...
        'Rev' ...
        'lRev' ...
        'sRev' ...
        'omegaUpsilon' ...
        'omega' ...
        'upsilon' ...
        'reori' ...
        'nonUpsilon_reori' ...
        'lRevOmega' ...
        'lRevUpsilon' ...
        'sRevOmega' ...
        'sRevUpsilon' ...
        'RevOmega' ...
        'RevOmegaUpsilon' ...
        'pause' ...
        'depause' ...
        'pure_Rev' ...
        'pure_omegaUpsilon' ...
        'pure_upsilon' ...
        'pure_omega' ...
        'pure_lRev' ...
        'pure_sRev'};
    
    k=1;
    for(i=1:length(freqfrac_bases))
        bindata_fieldnames{k} = sprintf('%s_freq',freqfrac_bases{i});
        k=k+1;
        bindata_fieldnames{k} = sprintf('frac_%s',freqfrac_bases{i});
        k=k+1;
    end
    
    instantaneous_fieldnames = { ...
        'speed' ...
        'angspeed' ...
        'ecc' ...
        'curv' ...
        'revlength' ...
        'revlength_bodybends' ...
        'revSpeed' ...
        'ecc_omegaupsilon' ...
        'delta_dir_omegaupsilon' ...
        'delta_dir_rev' ...
        'body_angle' ...
        'head_angle' ...
        'tail_angle' ...
        'uncorr_speed' ...
        'uncorr_ecc'};
    
    for(i=1:length(instantaneous_fieldnames))
        bindata_fieldnames{k} = instantaneous_fieldnames{i};
        k=k+1;
    end
end

if(nargin<1)
    correct_attributes = bindata_fieldnames;
    clear('bindata_fieldnames');
    return;
end

not_cell_flag=0;
if(~iscell(input_attributes))
    not_cell_flag = 1;
    dummy = input_attributes;
    input_attributes = [];
    input_attributes{1} = dummy;
    clear('dummy');
end


for(i=1:length(input_attributes))
    idx = find(strcmpi(bindata_fieldnames,input_attributes{i}));
    if(~isempty(idx))
        correct_attributes{i} = bindata_fieldnames{idx};
    else
        correct_attributes{i} = input_attributes{i};
    end
end

if(not_cell_flag==1)
    dummy = correct_attributes{1};
    clear('correct_attributes');
    correct_attributes = dummy;
    clear('dummy');
end

return;
end

